training_dataset: "data/FOCAL_wavedata/scaledup/IR_1.csv"
dof:
  - "wave1"
  - "wave2"
  - "wave3"
  - "wave4"
  - "wave5"
unit:
  - "[m]"
  - "[m]"
  - "[m]"
  - "[m]"
  - "[m]"
conversion:
  - 1
  - 1
  - 1
  - 1
  - 1
time_horizon: 171.3263190944316  # seconds
nm: 0.9543103644520594
hidden_layer: 2
neuron_number: 62
epochs: 124
batch_time: 80
timestep: 0.8344869191261223
lr: 0.022095466554539495
dropout: 0.017676155512857773
train_ratio: 0.50
valid_ratio: 0.25
wind_prediction: False
wave_prediction: False
